import './globals.css';
import Provider from 'client-provider';
import JeJuProvider from './jejuProvider';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Meta</title>
      <link rel="icon" href="/favicon.ico" />
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body>
        <JeJuProvider>
          <Provider>{children}</Provider>
        </JeJuProvider>
      </body>
    </html>
  );
}

// export const metadata = {
//   title: 'Sass Admin',
//   icons: '/favicon.ico'
// };

// export default function Head() {
//   return (
//     <>
//       <title>Saas Admin</title>
//       <meta content="width=device-width, initial-scale=1" name="viewport" />
//       <meta name="description" content="Generated by create next app" />
//       <link rel="shortcut icon" href="/favicon.ico" />
//     </>
//   )
// }
